[platformio]
default_envs = esp32-s3-touch-lcd-4

[env:esp32-s3-touch-lcd-4]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.32/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.mcu = esp32s3
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.partitions = partitions_16mb_ota.csv
board_build.arduino.memory_type = qio_opi

build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D BOARD_HAS_PSRAM
  -D CORE_DEBUG_LEVEL=3
  -I "C:/Users/26466/.platformio/packages/framework-arduinoespressif32/libraries/Network/src"

lib_extra_dirs =
  ../ESP32-S3-Touch-LCD-4-main/ESP32-S3-Touch-LCD-4-main/examples/Arduino-v3.3.2/libraries

lib_deps =
  bblanchon/ArduinoJson@^7.4.2

lib_ldf_mode = deep+

[env:esp32-s3-touch-lcd-4-ota]
extends = env:esp32-s3-touch-lcd-4
upload_protocol = espota
upload_port = home-net-panel.local
upload_flags =
  --auth=CC12369874
